/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.sistemaproductos;

import java.awt.Dimension;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jhone
 */
public class PantallaVenta extends javax.swing.JInternalFrame {

    /**
     * Creates new form PantallaVenta
     */
    double IVA = 0.19;

    private void actualizarTotal() {
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        double total_sinIVA = 0.0;

        for (int i = 0; i < model.getRowCount(); i++) {
            Object valor = model.getValueAt(i, 3); // Suponiendo que columna 3 es "Subtotal"
            if (valor != null && valor instanceof Number) {
                total_sinIVA += ((Number) valor).doubleValue();
            }
        }

        double montoIVA = total_sinIVA * IVA;
        double totalConIVA = total_sinIVA + montoIVA;

        txtTotalsinIva.setText(String.format("%.2f", total_sinIVA));
        txtIVA.setText(String.format("%.2f", montoIVA));
        txtTotalconIva.setText(String.format("%.2f", totalConIVA));
    }

    public PantallaVenta() {
        initComponents();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PantallaRegistro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtBProducto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        btnCarrito = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtTotalsinIva = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtIVA = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTotalconIva = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setPreferredSize(new java.awt.Dimension(500, 600));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Realizar Compra");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Producto :");

        txtBProducto.setText("Ingrese el Nombre del Producto");
        txtBProducto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBProductoFocusGained(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Cantidad :");

        txtCantidad.setText("Ingrese la Cantidad del Producto");
        txtCantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCantidadFocusGained(evt);
            }
        });

        btnCarrito.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCarrito.setText("Agregar al Carrito");
        btnCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarritoActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Cantidad", "Precio", "Subtotal"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton2.setText("Finalizar Venta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFinVenta(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("SubTotal (Sin IVA)$ :");

        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnQuitarVenta(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("IVA :");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("TOTAL(IVA)$ :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtCantidad))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtBProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnCarrito))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(txtTotalconIva, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtTotalsinIva, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(144, 144, 144)
                            .addComponent(jButton1))))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCarrito)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalsinIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButton1)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTotalconIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(72, 72, 72))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Boton para Agregar al carrito
    private void btnCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarritoActionPerformed
        // TODO add your handling code here:
        String nombreProducto = txtBProducto.getText().trim();
        String cantidadStr = txtCantidad.getText().trim();

        if (nombreProducto.isEmpty() || cantidadStr.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debes ingresar el producto y su  cantidad.");
            return;
        }

        int cantidad;

        try {
            cantidad = Integer.parseInt(cantidadStr);
            if (cantidad <= 0) {
                JOptionPane.showMessageDialog(null, "La cantidad debe ser mayor que 0.");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Cantidad inválida.");
            return;
        }

        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/sistemaproductos", "root", "");

            String sql = "SELECT * FROM productos WHERE LOWER(nombre) = LOWER(?)";
            PreparedStatement ps = con.prepareStatement(sql);

            ps.setString(1, nombreProducto);

            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                double precio = rs.getDouble("precio");

                int stock = rs.getInt("stock");

                if (cantidad > stock) {

                    JOptionPane.showMessageDialog(null, "Stock insuficiente. Solo hay " + stock + " unidades.");
                    return;
                }

                double subtotal = precio * cantidad;

                DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
                model.insertRow(0, new Object[]{
                    nombreProducto,
                    cantidad,
                    precio,
                    subtotal,});

                actualizarTotal();

                txtBProducto.setText("");
                txtCantidad.setText("");

                JOptionPane.showMessageDialog(null, "Producto agregado al carrito.");
            } else {

                JOptionPane.showMessageDialog(null, "Producto no encontrado.");

            }

        } catch (SQLException ex) {
            Logger.getLogger(PantallaVenta.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnCarritoActionPerformed

    private void txtBProductoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBProductoFocusGained
        // TODO add your handling code here:
        txtBProducto.setText("");

    }//GEN-LAST:event_txtBProductoFocusGained

    private void txtCantidadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidadFocusGained
        // TODO add your handling code here:
        txtCantidad.setText("");
    }//GEN-LAST:event_txtCantidadFocusGained

    private void BtnQuitarVenta(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnQuitarVenta
        // TODO add your handling code here:
        int filaSeleccionada = jTable2.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(null, "Selecciona un producto de la tabla para eliminar.");
            return;
        }
        int confirmacion = JOptionPane.showConfirmDialog(null, "¿Estás seguro de eliminar este producto?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
        if (confirmacion == JOptionPane.YES_OPTION) {
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            model.removeRow(filaSeleccionada);

            actualizarTotal();

            JOptionPane.showMessageDialog(null, "Producto eliminado correctamente.");
        }


    }//GEN-LAST:event_BtnQuitarVenta

    private void BtnFinVenta(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFinVenta
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        double tasaIVA = 0.19;

        StringBuilder factura = new StringBuilder();
        double totalSinIVA = 0.0;
        double totalIVA = 0.0;

        Connection conn = null;
        PreparedStatement psUpdate = null;

        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sistemaproductos", "root", "");
            conn.setAutoCommit(false);

            String sql = "UPDATE productos SET stock = stock - ? WHERE nombre = ?";
            psUpdate = conn.prepareStatement(sql);
            
            factura.append(String.format("%80s\n", "=== FACTURA ==="))
                   .append(String.format("%-15s %-12s %-10s %-12s %-12s %-12s\n",
                "Producto:", "Cantidad:", "Precio:", "Subtotal:", "IVA:", "Total con IVA:"));
            
            for (int i = 0; i < model.getRowCount(); i++) {
                // Validar que ninguna celda sea null
                Object objNombre = model.getValueAt(i, 0);
                Object objCantidad = model.getValueAt(i, 1);
                Object objPrecio = model.getValueAt(i, 2);

                if (objNombre == null || objCantidad == null || objPrecio == null) {
                    // Si hay una fila incompleta, se salta
                    continue;
                }

                String nombre = objNombre.toString();
                int cantidad = Integer.parseInt(objCantidad.toString());
                double precio = Double.parseDouble(objPrecio.toString());
                double subtotal = precio * cantidad;
                double iva = subtotal * tasaIVA;
                double totalConIVA = subtotal + iva;

                factura
                        .append(String.format("%-15s %12d %11.2f %13.2f %13.2f %13.2f\n",
                            nombre, cantidad, precio, subtotal, iva, totalConIVA));
                        
                psUpdate.setInt(1, cantidad);
                psUpdate.setString(2, nombre);
                psUpdate.executeUpdate();

                totalSinIVA += subtotal;
                totalIVA += iva;
            }

            conn.commit();

            double totalFinal = totalSinIVA + totalIVA;
            
            factura.append("========================================================\n");
            factura.append(String.format("%-37s %-12.2f\n", "TOTAL SIN IVA:", totalSinIVA));
            factura.append(String.format("%-37s %-12.2f\n", "TOTAL IVA:", totalIVA));
            factura.append(String.format("%-37s %-12.2f\n", "TOTAL FINAL:", totalFinal));

            System.out.println(factura.toString());
            JOptionPane.showMessageDialog(null, "Venta finalizada con éxito.");
            
            JTextArea textArea = new JTextArea(factura.toString());
            textArea.setEditable(false);
            textArea.setCaretPosition(0); // Mostrar desde arriba
            JScrollPane scrollPane = new JScrollPane(textArea);
            scrollPane.setPreferredSize(new Dimension(500, 400)); // Ajusta tamaño si deseas

            JOptionPane.showMessageDialog(null, scrollPane, "Factura de Venta", JOptionPane.INFORMATION_MESSAGE);

            // Limpiar la tabla y los campos
            model.setRowCount(0);
            txtTotalsinIva.setText(""); // o puedes poner totalFinal con formato
            // También puedes limpiar otros campos si los tienes

        } catch (HeadlessException | NumberFormatException | SQLException e) {
            try {
                if (conn != null) {
                    conn.rollback();
                }
            } catch (SQLException ex) {
            }
            JOptionPane.showMessageDialog(null, "Error al finalizar venta: " + e.getMessage());

        } finally {
            try {
                if (psUpdate != null) {
                    psUpdate.close();
                }
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException ex) {
            }
        }
    }//GEN-LAST:event_BtnFinVenta


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarrito;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtBProducto;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtIVA;
    private javax.swing.JTextField txtTotalconIva;
    private javax.swing.JTextField txtTotalsinIva;
    // End of variables declaration//GEN-END:variables
}
